import type { CheckDefinition, CheckKey } from "./types";

/** Controlled check registry — no dynamic code execution. */
export const CLOSE_CHECK_REGISTRY: Record<CheckKey, CheckDefinition> = {
  integration_sources_current: {
    key: "integration_sources_current",
    label: "Integration sources current",
    category: "DATA",
    description: "Hub readiness for P&L/AR is CURRENT (not stale, reconnect, or error).",
    kind: "AUTOMATED",
    blockingDefault: true,
    dependencyTags: ["integration"],
  },
  gate_pass: {
    key: "gate_pass",
    label: "Gate passes",
    category: "FINANCIAL_CHECKS",
    description: "Existing release gate ties (labor/payroll, cash, balance sheet rules).",
    kind: "AUTOMATED",
    blockingDefault: true,
    dependencyTags: ["ledger", "payroll", "cash", "balance"],
  },
  figures_present: {
    key: "figures_present",
    label: "Period figures present",
    category: "DATA",
    description: "Working period has revenue or payroll figures to close against.",
    kind: "AUTOMATED",
    blockingDefault: true,
    dependencyTags: ["ledger"],
  },
  doc_payroll_approved: {
    key: "doc_payroll_approved",
    label: "Payroll register approved",
    category: "DOCUMENTS",
    description: "Approved PAYROLL_REGISTER document linked to the period.",
    kind: "AUTOMATED",
    blockingDefault: true,
    dependencyTags: ["doc_payroll"],
  },
  doc_ar_approved: {
    key: "doc_ar_approved",
    label: "AR schedule approved",
    category: "DOCUMENTS",
    description: "Approved AR_SCHEDULE document linked to the period.",
    kind: "AUTOMATED",
    blockingDefault: true,
    dependencyTags: ["doc_ar"],
  },
  doc_debt_approved: {
    key: "doc_debt_approved",
    label: "Debt schedule approved",
    category: "DOCUMENTS",
    description: "Approved DEBT_SCHEDULE document linked to the period (when required).",
    kind: "AUTOMATED",
    blockingDefault: false,
    dependencyTags: ["doc_debt"],
  },
  recon_payroll: {
    key: "recon_payroll",
    label: "Payroll reconciliation",
    category: "RECONCILIATIONS",
    description: "Consumes reconciliation engine — MATCHED / WITHIN_TOLERANCE / RESOLVED.",
    kind: "AUTOMATED",
    blockingDefault: true,
    dependencyTags: ["ledger", "payroll", "doc_payroll", "recon_payroll"],
  },
  recon_ar: {
    key: "recon_ar",
    label: "AR reconciliation",
    category: "RECONCILIATIONS",
    description: "Consumes reconciliation engine AR result.",
    kind: "AUTOMATED",
    blockingDefault: true,
    dependencyTags: ["ledger", "ar", "doc_ar", "recon_ar"],
  },
  recon_debt: {
    key: "recon_debt",
    label: "Debt reconciliation",
    category: "RECONCILIATIONS",
    description: "Consumes reconciliation engine debt result.",
    kind: "AUTOMATED",
    blockingDefault: false,
    dependencyTags: ["balance", "doc_debt", "recon_debt"],
  },
  recon_no_critical_open: {
    key: "recon_no_critical_open",
    label: "No open critical recon exceptions",
    category: "RECONCILIATIONS",
    description: "No OPEN/ASSIGNED/UNDER_REVIEW CRITICAL accounting exceptions for the period.",
    kind: "AUTOMATED",
    blockingDefault: true,
    dependencyTags: ["recon_payroll", "recon_ar", "recon_debt"],
  },
  balance_sheet_balances: {
    key: "balance_sheet_balances",
    label: "Balance sheet balances",
    category: "FINANCIAL_CHECKS",
    description: "Assets − liabilities − equity ≈ 0 within tolerance when BS lines exist.",
    kind: "AUTOMATED",
    blockingDefault: true,
    dependencyTags: ["balance"],
  },
  cash_present: {
    key: "cash_present",
    label: "Cash balances present",
    category: "FINANCIAL_CHECKS",
    description: "Operating/reserve cash rows exist for the period.",
    kind: "AUTOMATED",
    blockingDefault: true,
    dependencyTags: ["cash"],
  },
  variance_revenue_mom: {
    key: "variance_revenue_mom",
    label: "Revenue MoM variance review",
    category: "VARIANCE_REVIEW",
    description: "Flags revenue moves above policy threshold for human review.",
    kind: "AUTOMATED",
    blockingDefault: true,
    dependencyTags: ["ledger"],
  },
  variance_payroll_mom: {
    key: "variance_payroll_mom",
    label: "Payroll MoM variance review",
    category: "VARIANCE_REVIEW",
    description: "Flags payroll moves above policy threshold for human review.",
    kind: "AUTOMATED",
    blockingDefault: true,
    dependencyTags: ["payroll", "ledger"],
  },
  variance_opex_mom: {
    key: "variance_opex_mom",
    label: "OpEx MoM variance review",
    category: "VARIANCE_REVIEW",
    description: "Flags operating expense moves above policy threshold.",
    kind: "AUTOMATED",
    blockingDefault: false,
    dependencyTags: ["ledger"],
  },
  manual_unusual_entries: {
    key: "manual_unusual_entries",
    label: "Reviewed unusual journal entries",
    category: "ACCOUNTING_REVIEW",
    description: "Manual staff attestation — not automated.",
    kind: "MANUAL",
    blockingDefault: false,
    dependencyTags: [],
  },
  manual_related_party: {
    key: "manual_related_party",
    label: "Reviewed related-party activity",
    category: "ACCOUNTING_REVIEW",
    description: "Manual staff attestation — not automated.",
    kind: "MANUAL",
    blockingDefault: false,
    dependencyTags: [],
  },
  commentary_present: {
    key: "commentary_present",
    label: "Advisor commentary complete",
    category: "ADVISOR_REVIEW",
    description: "Real WHAT_CHANGED notes present (same bar as release evaluate).",
    kind: "AUTOMATED",
    blockingDefault: true,
    dependencyTags: ["commentary"],
  },
  publish_evaluate_clear: {
    key: "publish_evaluate_clear",
    label: "Existing release evaluate clear",
    category: "PUBLISHING_READINESS",
    description: "lib/release.evaluate has no blockers (does not publish).",
    kind: "AUTOMATED",
    blockingDefault: true,
    dependencyTags: ["ledger", "commentary", "gate"],
  },
};

export const FIRM_DEFAULT_CHECK_KEYS: CheckKey[] = [
  "integration_sources_current",
  "figures_present",
  "gate_pass",
  "doc_payroll_approved",
  "doc_ar_approved",
  "doc_debt_approved",
  "recon_payroll",
  "recon_ar",
  "recon_debt",
  "recon_no_critical_open",
  "balance_sheet_balances",
  "cash_present",
  "variance_revenue_mom",
  "variance_payroll_mom",
  "variance_opex_mom",
  "manual_unusual_entries",
  "commentary_present",
  "publish_evaluate_clear",
];

export function getCheckDef(key: CheckKey): CheckDefinition {
  const d = CLOSE_CHECK_REGISTRY[key];
  if (!d) throw new Error(`Unknown close check: ${key}`);
  return d;
}
